name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: test
      run: pwd
    - name: Grant sml execute permission for gradlew
      run: chmod +x sml/gradlew
    - name: Build sml with Gradle
      run: ./sml/gradlew publish -p sml
      
    - name: Grant execute permission for gradlew
      run: chmod +x common-ui-list-structure/gradlew
    - name: Build with Gradle
      run: ./common-ui-list-structure/gradlew build -p common-ui-list-structure
      
    - name: test2
      run: ls -R
    - uses: noriban/sign-android-release@v3
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: common-ui-list-structure/app/giant-explorer/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "33.0.1"
    - uses: noriban/sign-android-release@v3
      name: Sign app APK
      # ID used to access action output
      id: sign_ping_app
      with:
        releaseDirectory: common-ui-list-structure/app/ping/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "33.0.1"

    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v3
      with:
        name: Signed app bundle
        path: |
          ${{steps.sign_app.outputs.signedReleaseFile}}
          ${{steps.sign_ping_app.outputs.signedReleaseFile}}
